FROM golang:1.17-alpine3.15
WORKDIR /app
COPY . .
# strip additional debug information from
RUN go build -o application main.go
# RUN go build -ldflags '-w -s -extldflags "-static"' -a -o application main.go

FROM alpine:latest
WORKDIR /app
COPY --from=0 /app ./
CMD ["./application"]