apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo2-deployment
  labels:
    app: echo2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo2
  template:
    metadata:
      labels:
        app: echo2
    spec:
      containers:
        - name: echo2
          image: 20220327.azurecr.io/echo2:v3
          ports:
            - containerPort: 8080
