apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mcf-hpa
spec:
  maxReplicas: 5 # define max replica count
  #minReplicas:   # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # name: mcf
    name: mcf-deployment
  targetCPUUtilizationPercentage: 5 # target CPU utilization
