apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcf-deployment
  namespace: mcf
  labels:
    app: mcf-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcf
  template:
    metadata:
      labels:
        app: mcf
    spec:
      containers:
        - name: mcf
          image: acr9oct.azurecr.io/mcf:v1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 150Mi
          ports:
            - containerPort: 8080
